apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: test-nov28-fouronefive
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-nov28-fouronefive 
  name: test-nov28-fouronefive
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: test-nov28-fouronefive 
